title: Ashley Blawas
logo: /assets/img/logo-circle.JPG
gs: /assets/img/gs.png
rg: /assets/img/rg.png
orciid: /assets/img/orciid.png
cv: /assets/docs/ABLAWAS_CV.pdf
description: Ph.D. Student & Comparative Physiologist
show_downloads: false
#google_analytics:
theme: jekyll-theme-minimal
