title: Ashley Blawas
logo: /assets/img/logo-circle.JPG
gs: /assets/img/gs.png
rg: /assets/img/rg.png
orciid: /assets/img/orciid.png
description: Researcher at the intersection of Physiology, Engineering, and Marine Science
show_downloads: false
#google_analytics:
theme: jekyll-theme-minimal
