title: Ashley Blawas
logo: /assets/img/logo-circle.JPG
logo: /assets/img/gs.png
description: Ph.D. Student & Comparative Physiologist
show_downloads: false
#google_analytics:
theme: jekyll-theme-minimal
